### ISSUE TITLE
Download status not shown in terminal

### ISSUE THREAD

**Issue by kritisingh1** [OpenHumans/open-humans-api#13]
When we run the command `ohpub-download` , download status (whether it is complete or not and if not, then the percentage completion) is not shown in the terminal which leaves the user in suspicion whether the download is complete or is still running. 
Also, it does not exit by default.

**Comment by gedankenstuecke** [comment]
Fully agree, this would be good to have. I recently used it to download a large number of files too and it was confusing to not get any feedback. Do you want to give it a try?

**Comment by kritisingh1** [comment]
Yeah. I would definitely work on this. Thanks :smile:

**Comment by gedankenstuecke** [comment]
Awesome, thanks!

**Comment by madprime** [comment]
When the command line function is run with `--verbose` or `--debug` flags, it does produce output.

A couple questions...
1. @gedankenstuecke and @kritisingh1 were you aware of these flags?
2. Which do you think the default behavior should be? (INFO, DEBUG, or quiet?)

I don't think the default behavior should be DEBUG, but I'm open to the other two as options. (I'm calling the current behavior "quiet".)

If we'd like to switch to INFO level output as default (which is currently triggered with the `--verbose` flag), I think the logic should be changed so we instead have a flag `-q / --quiet` flag where logging isn't set (current approach), or is set to a higher level, like WARNING or ERROR.

**Comment by kritisingh1** [comment]
Sure, so shall I make `INFO` as the default behavior and replace `verbose` flag with `quiet` ? I will make the required changes as soon as you affirm these expected changes. @madprime . Thanks!

**Comment by madprime** [comment]
Per Slack discussion – this sounds good, let's do this. Thanks @kritisingh1!

**Comment by kritisingh1** [comment]
Closed via #17
