### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans-api#14]
So far none of our functions have tests that could be run by a continuous integration. Having these would be great for making all of our lives easier. 

The OSFclient has some examples of how to test API code in Python that could be an inspiration: https://github.com/osfclient/osfclient/tree/master/osfclient/tests

**Comment by shubhangi-chauhan** [comment]
On it!

**Comment by kritisingh1** [comment]
@shubhangi-chauhan can you mention which functions are you working on (for adding tests) currently? So that duplicate efforts could be avoided. Thanks :slightly_smiling_face:

**Comment by madprime** [comment]
Maybe use https://pypi.python.org/pypi/requests-mock (@gedankenstuecke found this later and shared the link with me).

And I want the `api.py` functions to have tests and CI set up before considering PRs that change this code.

**Comment by shubhangi-chauhan** [comment]
@kritisingh1 Hi, I'm writing tests for the CLI

**Comment by kritisingh1** [comment]
@rosygupta I am working on the public.py part.

**Comment by DartingMelody** [comment]
hey @kritisingh1 , @rosygupta, @shubhangi-chauhan just need to inform that I am already working on the tests for upload_file function of api.py. Thanks :)

**Comment by kritisingh1** [comment]
Just wanted to inform that I am working on the tests to be added for ohapi/projects.py. Thanks :)
@DartingMelody @rosygupta

**Comment by DartingMelody** [comment]
@kritisingh1 , since there are so many functions in projects.py. It would be better if we both work on it together so that the work is finished earlier. I had actually started working on upload_member_from_dir and download_member_shared functions. :)

**Comment by kritisingh1** [comment]
Better that you informed @DartingMelody  other wise our PRs would have clashed. Nevertheless, I will work on other functions and the remaining ones of utils_fs.py

**Comment by rosygupta** [comment]
@DartingMelody @kritisingh1 I could pitch in too if anyone of you could summarise which all tests (in total) are left. :)

**Comment by DartingMelody** [comment]
@rosygupta @kritisingh1 actually there are many functions in utlil_fs.py for which tests are not written.  @rosygupta you could quickly cross reference which tests are left and work on them :)

**Comment by rosygupta** [comment]
@DartingMelody yea right! There's no good nomenclature for the existing tests which makes it a lil difficult to match up. That's why asked you guys since you were active right now. Anyway I'll figure it out. Like you mentioned utils_fs.py does have a lot of functions left for testing, and you both have already a lot on your plate (these tests, documentation and a couple more open PRs) and I got none, I'll work on those. We shouldn't be hoarding work here. :) Please confirm if both of you are good with it?

**Comment by DartingMelody** [comment]
Exactly, I feel the same(for the hoarding one ;) ). Feel free to work  :)

**Comment by rosygupta** [comment]
@kritisingh1 can you please specify which ones will you be taking up?

**Comment by kritisingh1** [comment]
@rosygupta just one function remains in utils_fs.py and I am on it :) namely `mk_metadata_csv`

**Comment by rosygupta** [comment]
@kritisingh1 can you also specify which one's are left? since they aren't placed in a good file structure. It would be really helpful.

**Comment by kritisingh1** [comment]
Hi. I am working on the tests for `download_member_project_data` and `download_all` functions in OHProject for now. :)

**Comment by kritisingh1** [comment]
@DartingMelody just needed to inform that I have started working on adding tests for the function `upload_aws` so that efforts do not duplicate. Thanks :)

**Comment by DartingMelody** [comment]
Hi @kritisingh1 , I was thinking to work on tests for upload_aws but as I have two other claimed test to complete, it's fine with me. Since, it's the same with you(two claimed tests), you should check with @rosygupta once. She was quite interested to work on tests a few day back. Thanks :)

**Comment by kritisingh1** [comment]
The other two tests were being delayed due to the runtime file generation issue. Since that is solved it won't take much time now. :)

**Comment by DartingMelody** [comment]
Even then, you can go ahead and check with @rosygupta once, she was quite enthusiastic to work on tests earlier and she was quite vocal about it on slack too. Ofcourse, if @rosygupta doesn't want to work on it, you can go ahead. It's fine with me :)
