### ISSUE TITLE
Make API errors more clear

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans-api#16]
Currently, when API calls fail, they fail silently – functions in `ohapi/api.py` aren't returning information that makes an API error clear.

I think the best way to expose these errors is to raise a custom Exception when the API response indicates an error.

Contributions to add this feature can focus on adding this to specific functions, one at a time.

**Comment by DartingMelody** [comment]
Hi, @madprime , I am taking this issue (especially on message function). Thanks.

**Comment by madprime** [comment]
To clarify this issue: there are times an API call "succeeds" (a request was made and the server responded) – but the content of what the API returns indicates an error occurred.

If one stores and checks an API response (e.g. in the `message` function, where it's not currently checked), that response may indicate an error occurred. This should raise a (custom) Exception.

For example...
```
>>> req.status_code
401
>>> req.json()
{'detail': 'Invalid token.'}
```

**Comment by kritisingh1** [comment]
@dibyadas PR #30 is still under progress. As @madprime has suggested in this issue before, the goal is to make the functions throw custom exceptions only. Besides , I need to refactor some parts of the code too. Thanks for reviewing.
