### ISSUE TITLE
Update Upload function

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans-api#4]
The Upload function should be implemented with the AWS S3 upload method to also allow for larger files to be transferred.

**Comment by kritisingh1** [comment]
@gedankenstuecke I am taking this up! Thanks :)

**Comment by gedankenstuecke** [comment]
Great, thanks!

**Comment by DartingMelody** [comment]
@gedankenstuecke Can I too work on this issue ??

**Comment by sepicoder** [comment]
I would like to work on this :)

**Comment by gedankenstuecke** [comment]
Thanks for the interest @sepicoder, but this is nearly ready with #31 which just needs a final review before being merged.
