### ISSUE TITLE
Build fails now

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans-api#51]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
Our build fails right now, c.f. https://travis-ci.org/OpenHumans/open-humans-api/builds/355909723

It's this test that fails: https://github.com/OpenHumans/open-humans-api/blob/master/ohapi/tests/test_test.py#L94

It was added in #32 by @kritisingh1 and I think the test itself is broken rather than the code it tries to test. It relates to the md5 sums not being identical any more. I think this goes back to the files being created during the test runtime. @kritisingh1 can you please look into this?

**Comment by kritisingh1** [comment]
Yeah sure. I will fix this asap. Sorry for the incovenience
