### ISSUE TITLE
Make project_member_id not required for upload_file

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans-api#7]
When calling the `upload_file` function you have to give the `project_member_id` as the API call requires this. I think it would be nice if this could be optional as it only makes sense if you've already called `exchange_oauth2_member` on your own (or if you already have stored the `project_member_id`).

If you're not providing the `project_member_id` it could just run `exchange_oauth2_member` itself and get the `project_member_id` that way.

**Comment by PallaviDas07** [comment]
I am working in this.

**Comment by gedankenstuecke** [comment]
Great, thanks!
