### ISSUE TITLE
Enable upload from file object instead of file path

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans-api#87]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
@jasmine1997 suggested updating to allow for uploading in memory files, rather than assuming files will be available locally via a filepath. Technically this means making the upload functions accept a file object, rather than a filepath -- this is more generic. c.f. https://docs.python.org/3/glossary.html#term-file-object

The current functionality should be retained, but as a wrapper that opens the file from filepath and passes the file object to the function.

**Comment by DartingMelody** [comment]
Hi @madprime, The code looks good to me. +1:
